from django.forms import ModelForm
from trades.models import Trade


class TradeForm(ModelForm):
    """Represents a form of the Trade model.
    The ID and date booked are autogenerated, so they don't
    apper in the form.
    """
    class Meta:
        model = Trade
        fields = [
            'sell_currency',
            'sell_amount',
            'buy_currency',
            'buy_amount',
            'rate'
        ]
